# Generated by Django 4.0.4 on 2022-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_content_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='number_of_users_rated',
            field=models.IntegerField(default=0),
        ),
    ]
